name: overhang
version: '0.0.0'
github: "jship/overhang"
license: MIT
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: Hang loose with your lambdas!
description: Combinators for clean, "hanging" lambdas.
category: Combinators, Functions, Utility
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall -Werror
library:
  dependencies:
  - base
  source-dirs: library
